/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Security status returned from enforcement checks */
export interface SecurityStatus {
  /** Whether the operation is allowed */
  allowed: boolean
  /** Reason for the decision */
  reason: string
  /** List of policy violations */
  violations: Array<string>
}
/** Result of a file read operation */
export interface ReadFileResult {
  /** File contents (if allowed and successful) */
  data?: Buffer
  /** Security status */
  status: SecurityStatus
}
/** Network request validation result */
export interface NetworkCheckResult {
  /** Whether the request is allowed */
  allowed: boolean
  /** Reason for the decision */
  reason: string
  /** Detected violations */
  violations: Array<string>
}
/** Process execution validation result */
export interface ProcessCheckResult {
  /** Whether the command is allowed */
  allowed: boolean
  /** Reason for the decision */
  reason: string
  /** Detected violations */
  violations: Array<string>
}
/** Simple API: Read file with security check */
export declare function readFileSecure(policyPath: string, filePath: string): ReadFileResult
/** Simple API: Check if path can be read */
export declare function checkReadAccess(policyPath: string, filePath: string): SecurityStatus
/** Simple API: Check network request */
export declare function checkNetworkRequest(policyPath: string, domain: string): NetworkCheckResult
/** Simple API: Check command execution */
export declare function checkCommandExecution(policyPath: string, command: string): ProcessCheckResult
/** OpenClaw Enforce - Native security enforcement */
export declare class EnforcementEngine {
  /** Create a new enforcement engine with a policy file */
  constructor(policyPath: string)
  /** Read a file with security checks */
  readFileSync(path: string): ReadFileResult
  /** Check if a path can be read without actually reading it */
  canRead(path: string): SecurityStatus
  /** Check if a path can be written to */
  canWrite(path: string): SecurityStatus
  /** Check if a network request is allowed */
  canNetworkRequest(domain: string): NetworkCheckResult
  /** Check if a command can be executed */
  canExecuteCommand(command: string): ProcessCheckResult
  /** Get policy statistics */
  getPolicyStats(): string
}
