// This file is @generated by prost-build.
/// File system messages
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadFileRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub capability: ::core::option::Option<Capability>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadFileResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub status: ::core::option::Option<SecurityStatus>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteFileRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub capability: ::core::option::Option<Capability>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteFileResponse {
    #[prost(message, optional, tag = "1")]
    pub status: ::core::option::Option<SecurityStatus>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListDirectoryRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub capability: ::core::option::Option<Capability>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListDirectoryResponse {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<FileEntry>,
    #[prost(message, optional, tag = "2")]
    pub status: ::core::option::Option<SecurityStatus>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileEntry {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_directory: bool,
    #[prost(uint64, tag = "4")]
    pub size: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteFileRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub capability: ::core::option::Option<Capability>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteFileResponse {
    #[prost(message, optional, tag = "1")]
    pub status: ::core::option::Option<SecurityStatus>,
}
/// Network messages
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpRequestData {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub method: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub headers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(bytes = "vec", tag = "4")]
    pub body: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "5")]
    pub capability: ::core::option::Option<Capability>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpResponseData {
    #[prost(int32, tag = "1")]
    pub status_code: i32,
    #[prost(map = "string, string", tag = "2")]
    pub headers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(bytes = "vec", tag = "3")]
    pub body: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub security_status: ::core::option::Option<SecurityStatus>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DnsLookupRequest {
    #[prost(string, tag = "1")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub capability: ::core::option::Option<Capability>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DnsLookupResponse {
    #[prost(string, repeated, tag = "1")]
    pub ip_addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "2")]
    pub status: ::core::option::Option<SecurityStatus>,
}
/// Process execution messages
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteCommandRequest {
    #[prost(string, tag = "1")]
    pub command: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "3")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "4")]
    pub working_dir: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub capability: ::core::option::Option<Capability>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteCommandResponse {
    #[prost(int32, tag = "1")]
    pub exit_code: i32,
    #[prost(string, tag = "2")]
    pub stdout: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub stderr: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub status: ::core::option::Option<SecurityStatus>,
}
/// Capability messages
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Capability {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Unix timestamp
    #[prost(int64, tag = "4")]
    pub expires_at: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CapabilityRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub requested_permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag = "3")]
    pub duration_seconds: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CapabilityResponse {
    #[prost(message, optional, tag = "1")]
    pub capability: ::core::option::Option<Capability>,
    #[prost(message, optional, tag = "2")]
    pub status: ::core::option::Option<SecurityStatus>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeRequest {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeResponse {
    #[prost(message, optional, tag = "1")]
    pub status: ::core::option::Option<SecurityStatus>,
}
/// Status and audit messages
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StatusRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusResponse {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub healthy: bool,
    #[prost(message, optional, tag = "3")]
    pub active_policy: ::core::option::Option<PolicyInfo>,
    #[prost(message, optional, tag = "4")]
    pub resources: ::core::option::Option<ResourceUsage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PolicyInfo {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub loaded_at: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ResourceUsage {
    #[prost(uint64, tag = "1")]
    pub memory_bytes: u64,
    #[prost(double, tag = "2")]
    pub cpu_percent: f64,
    #[prost(uint32, tag = "3")]
    pub active_connections: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuditLogRequest {
    #[prost(int64, tag = "1")]
    pub since_timestamp: i64,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub event_types: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuditLogEntry {
    #[prost(int64, tag = "1")]
    pub timestamp: i64,
    #[prost(string, tag = "2")]
    pub event_type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub operation: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub resource: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub allowed: bool,
    #[prost(string, tag = "7")]
    pub reason: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "8")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Common messages
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SecurityStatus {
    #[prost(bool, tag = "1")]
    pub allowed: bool,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub violations: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Generated client implementations.
pub mod enforcement_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Security enforcement service
    #[derive(Debug, Clone)]
    pub struct EnforcementServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl EnforcementServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> EnforcementServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> EnforcementServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            EnforcementServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// File system operations
        pub async fn read_file(
            &mut self,
            request: impl tonic::IntoRequest<super::ReadFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReadFileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/openclaw.enforce.EnforcementService/ReadFile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("openclaw.enforce.EnforcementService", "ReadFile"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn write_file(
            &mut self,
            request: impl tonic::IntoRequest<super::WriteFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WriteFileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/openclaw.enforce.EnforcementService/WriteFile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("openclaw.enforce.EnforcementService", "WriteFile"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_directory(
            &mut self,
            request: impl tonic::IntoRequest<super::ListDirectoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListDirectoryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/openclaw.enforce.EnforcementService/ListDirectory",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "openclaw.enforce.EnforcementService",
                        "ListDirectory",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_file(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteFileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/openclaw.enforce.EnforcementService/DeleteFile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("openclaw.enforce.EnforcementService", "DeleteFile"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Network operations
        pub async fn http_request(
            &mut self,
            request: impl tonic::IntoRequest<super::HttpRequestData>,
        ) -> std::result::Result<
            tonic::Response<super::HttpResponseData>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/openclaw.enforce.EnforcementService/HttpRequest",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("openclaw.enforce.EnforcementService", "HttpRequest"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn dns_lookup(
            &mut self,
            request: impl tonic::IntoRequest<super::DnsLookupRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DnsLookupResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/openclaw.enforce.EnforcementService/DnsLookup",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("openclaw.enforce.EnforcementService", "DnsLookup"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Process execution
        pub async fn execute_command(
            &mut self,
            request: impl tonic::IntoRequest<super::ExecuteCommandRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExecuteCommandResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/openclaw.enforce.EnforcementService/ExecuteCommand",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "openclaw.enforce.EnforcementService",
                        "ExecuteCommand",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Capability management
        pub async fn request_capability(
            &mut self,
            request: impl tonic::IntoRequest<super::CapabilityRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CapabilityResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/openclaw.enforce.EnforcementService/RequestCapability",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "openclaw.enforce.EnforcementService",
                        "RequestCapability",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn revoke_capability(
            &mut self,
            request: impl tonic::IntoRequest<super::RevokeRequest>,
        ) -> std::result::Result<tonic::Response<super::RevokeResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/openclaw.enforce.EnforcementService/RevokeCapability",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "openclaw.enforce.EnforcementService",
                        "RevokeCapability",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Health and status
        pub async fn get_status(
            &mut self,
            request: impl tonic::IntoRequest<super::StatusRequest>,
        ) -> std::result::Result<tonic::Response<super::StatusResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/openclaw.enforce.EnforcementService/GetStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("openclaw.enforce.EnforcementService", "GetStatus"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_audit_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::AuditLogRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::AuditLogEntry>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/openclaw.enforce.EnforcementService/GetAuditLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "openclaw.enforce.EnforcementService",
                        "GetAuditLogs",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod enforcement_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with EnforcementServiceServer.
    #[async_trait]
    pub trait EnforcementService: std::marker::Send + std::marker::Sync + 'static {
        /// File system operations
        async fn read_file(
            &self,
            request: tonic::Request<super::ReadFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReadFileResponse>,
            tonic::Status,
        >;
        async fn write_file(
            &self,
            request: tonic::Request<super::WriteFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WriteFileResponse>,
            tonic::Status,
        >;
        async fn list_directory(
            &self,
            request: tonic::Request<super::ListDirectoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListDirectoryResponse>,
            tonic::Status,
        >;
        async fn delete_file(
            &self,
            request: tonic::Request<super::DeleteFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteFileResponse>,
            tonic::Status,
        >;
        /// Network operations
        async fn http_request(
            &self,
            request: tonic::Request<super::HttpRequestData>,
        ) -> std::result::Result<
            tonic::Response<super::HttpResponseData>,
            tonic::Status,
        >;
        async fn dns_lookup(
            &self,
            request: tonic::Request<super::DnsLookupRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DnsLookupResponse>,
            tonic::Status,
        >;
        /// Process execution
        async fn execute_command(
            &self,
            request: tonic::Request<super::ExecuteCommandRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExecuteCommandResponse>,
            tonic::Status,
        >;
        /// Capability management
        async fn request_capability(
            &self,
            request: tonic::Request<super::CapabilityRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CapabilityResponse>,
            tonic::Status,
        >;
        async fn revoke_capability(
            &self,
            request: tonic::Request<super::RevokeRequest>,
        ) -> std::result::Result<tonic::Response<super::RevokeResponse>, tonic::Status>;
        /// Health and status
        async fn get_status(
            &self,
            request: tonic::Request<super::StatusRequest>,
        ) -> std::result::Result<tonic::Response<super::StatusResponse>, tonic::Status>;
        /// Server streaming response type for the GetAuditLogs method.
        type GetAuditLogsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::AuditLogEntry, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn get_audit_logs(
            &self,
            request: tonic::Request<super::AuditLogRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::GetAuditLogsStream>,
            tonic::Status,
        >;
    }
    /// Security enforcement service
    #[derive(Debug)]
    pub struct EnforcementServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> EnforcementServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for EnforcementServiceServer<T>
    where
        T: EnforcementService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/openclaw.enforce.EnforcementService/ReadFile" => {
                    #[allow(non_camel_case_types)]
                    struct ReadFileSvc<T: EnforcementService>(pub Arc<T>);
                    impl<
                        T: EnforcementService,
                    > tonic::server::UnaryService<super::ReadFileRequest>
                    for ReadFileSvc<T> {
                        type Response = super::ReadFileResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReadFileRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EnforcementService>::read_file(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReadFileSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/openclaw.enforce.EnforcementService/WriteFile" => {
                    #[allow(non_camel_case_types)]
                    struct WriteFileSvc<T: EnforcementService>(pub Arc<T>);
                    impl<
                        T: EnforcementService,
                    > tonic::server::UnaryService<super::WriteFileRequest>
                    for WriteFileSvc<T> {
                        type Response = super::WriteFileResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WriteFileRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EnforcementService>::write_file(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WriteFileSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/openclaw.enforce.EnforcementService/ListDirectory" => {
                    #[allow(non_camel_case_types)]
                    struct ListDirectorySvc<T: EnforcementService>(pub Arc<T>);
                    impl<
                        T: EnforcementService,
                    > tonic::server::UnaryService<super::ListDirectoryRequest>
                    for ListDirectorySvc<T> {
                        type Response = super::ListDirectoryResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListDirectoryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EnforcementService>::list_directory(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListDirectorySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/openclaw.enforce.EnforcementService/DeleteFile" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteFileSvc<T: EnforcementService>(pub Arc<T>);
                    impl<
                        T: EnforcementService,
                    > tonic::server::UnaryService<super::DeleteFileRequest>
                    for DeleteFileSvc<T> {
                        type Response = super::DeleteFileResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteFileRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EnforcementService>::delete_file(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteFileSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/openclaw.enforce.EnforcementService/HttpRequest" => {
                    #[allow(non_camel_case_types)]
                    struct HttpRequestSvc<T: EnforcementService>(pub Arc<T>);
                    impl<
                        T: EnforcementService,
                    > tonic::server::UnaryService<super::HttpRequestData>
                    for HttpRequestSvc<T> {
                        type Response = super::HttpResponseData;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HttpRequestData>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EnforcementService>::http_request(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HttpRequestSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/openclaw.enforce.EnforcementService/DnsLookup" => {
                    #[allow(non_camel_case_types)]
                    struct DnsLookupSvc<T: EnforcementService>(pub Arc<T>);
                    impl<
                        T: EnforcementService,
                    > tonic::server::UnaryService<super::DnsLookupRequest>
                    for DnsLookupSvc<T> {
                        type Response = super::DnsLookupResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DnsLookupRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EnforcementService>::dns_lookup(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DnsLookupSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/openclaw.enforce.EnforcementService/ExecuteCommand" => {
                    #[allow(non_camel_case_types)]
                    struct ExecuteCommandSvc<T: EnforcementService>(pub Arc<T>);
                    impl<
                        T: EnforcementService,
                    > tonic::server::UnaryService<super::ExecuteCommandRequest>
                    for ExecuteCommandSvc<T> {
                        type Response = super::ExecuteCommandResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ExecuteCommandRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EnforcementService>::execute_command(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExecuteCommandSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/openclaw.enforce.EnforcementService/RequestCapability" => {
                    #[allow(non_camel_case_types)]
                    struct RequestCapabilitySvc<T: EnforcementService>(pub Arc<T>);
                    impl<
                        T: EnforcementService,
                    > tonic::server::UnaryService<super::CapabilityRequest>
                    for RequestCapabilitySvc<T> {
                        type Response = super::CapabilityResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CapabilityRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EnforcementService>::request_capability(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RequestCapabilitySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/openclaw.enforce.EnforcementService/RevokeCapability" => {
                    #[allow(non_camel_case_types)]
                    struct RevokeCapabilitySvc<T: EnforcementService>(pub Arc<T>);
                    impl<
                        T: EnforcementService,
                    > tonic::server::UnaryService<super::RevokeRequest>
                    for RevokeCapabilitySvc<T> {
                        type Response = super::RevokeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RevokeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EnforcementService>::revoke_capability(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RevokeCapabilitySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/openclaw.enforce.EnforcementService/GetStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetStatusSvc<T: EnforcementService>(pub Arc<T>);
                    impl<
                        T: EnforcementService,
                    > tonic::server::UnaryService<super::StatusRequest>
                    for GetStatusSvc<T> {
                        type Response = super::StatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EnforcementService>::get_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/openclaw.enforce.EnforcementService/GetAuditLogs" => {
                    #[allow(non_camel_case_types)]
                    struct GetAuditLogsSvc<T: EnforcementService>(pub Arc<T>);
                    impl<
                        T: EnforcementService,
                    > tonic::server::ServerStreamingService<super::AuditLogRequest>
                    for GetAuditLogsSvc<T> {
                        type Response = super::AuditLogEntry;
                        type ResponseStream = T::GetAuditLogsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AuditLogRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EnforcementService>::get_audit_logs(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAuditLogsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for EnforcementServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "openclaw.enforce.EnforcementService";
    impl<T> tonic::server::NamedService for EnforcementServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
